var DISQUS=function(f){var e={AssertionError:function(d){this.message=d}};e.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};e.assert=function(d,f){if(!d)throw new e.AssertionError(f);};var l=[];e.define=function(d,i){typeof d==="function"&&(i=d,d="");for(var b=d.split("."),a=b.shift(),c=e,g=(i||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;return a}},f);a;)c=c[a]?c[a]:c[a]={},a=b.shift();for(var k in g)g.hasOwnProperty(k)&&
(g.__overwrites__||c[k]!==null&&e.assert(!c.hasOwnProperty(k),"Unsafe attempt to redefine existing module with "+k),c[k]=g[k],l.push(function(a,b){return function(){delete a[b]}}(c,k)));return c};e.use=function(d){return e.define(d)};e.cleanup=function(){for(var d=0;d<l.length;d++)l[d]()};return e}(this);
DISQUS.define(function(f,e){var l=f.document,d=l.getElementsByTagName("head")[0]||l.body,i={running:!1,timer:null,queue:[]};DISQUS.defer=function(b,a){function c(){var a=i.queue;if(a.length===0)i.running=!1,clearInterval(i.timer);for(var b=0,c;c=a[b];b++)c[0]()&&(a.splice(b--,1),c[1]())}i.queue.push([b,a]);c();if(!i.running)i.running=!0,i.timer=setInterval(c,100)};DISQUS.each=function(b,a){var c=b.length,g=Array.prototype.forEach;if(isNaN(c))for(var d in b)b.hasOwnProperty(d)&&a(b[d],d,b);else if(g)g.call(b,
a);else for(g=0;g<c;g++)a(b[g],g,b)};DISQUS.extend=function(b){DISQUS.each(Array.prototype.slice.call(arguments,1),function(a){for(var c in a)b[c]=a[c]});return b};DISQUS.serializeArgs=function(b){var a=[];DISQUS.each(b,function(b,g){b!==e&&a.push(g+(b!==null?"="+encodeURIComponent(b):""))});return a.join("&")};DISQUS.isString=function(b){return Object.prototype.toString.call(b)==="[object String]"};DISQUS.serialize=function(b,a,c){a&&(b+=~b.indexOf("?")?b.charAt(b.length-1)=="&"?"":"&":"?",b+=DISQUS.serializeArgs(a));
if(c)return a={},a[(new Date).getTime()]=null,DISQUS.serialize(b,a);a=b.length;return b.charAt(a-1)=="&"?b.slice(0,a-1):b};DISQUS.require=function(b,a,c,g,f){function e(j){if(j.type=="load"||/^(complete|loaded)$/.test(j.target.readyState))g&&g(),n&&clearTimeout(n),DISQUS.bean.remove(j.target,h,e)}var i=l.createElement("script"),h=i.addEventListener?"load":"readystatechange",n=null;i.src=DISQUS.serialize(b,a,c);i.async=!0;i.charset="UTF-8";(g||f)&&DISQUS.bean.add(i,h,e);f&&(n=setTimeout(function(){f()},
2E4));d.appendChild(i);return DISQUS};DISQUS.requireStylesheet=function(b,a,c){var g=l.createElement("link");g.rel="stylesheet";g.type="text/css";g.href=DISQUS.serialize(b,a,c);d.appendChild(g);return DISQUS};DISQUS.requireSet=function(b,a,c){var g=b.length;DISQUS.each(b,function(b){DISQUS.require(b,{},a,function(){--g===0&&c()})})};DISQUS.injectCss=function(b){var a=l.createElement("style");a.setAttribute("type","text/css");b=b.replace(/\}/g,"}\n");f.location.href.match(/^https/)&&(b=b.replace(/http:\/\//g,
"https://"));a.styleSheet?a.styleSheet.cssText=b:a.appendChild(l.createTextNode(b));d.appendChild(a)}});
DISQUS.define("JSON",function(){function f(j){return j<10?"0"+j:j}function e(j){a.lastIndex=0;return a.test(j)?'"'+j.replace(a,function(j){var a=k[j];return typeof a==="string"?a:"\\u"+("0000"+j.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+j+'"'}function l(j,a){var b,n,m,d,f=c,h,q=a[j];q&&typeof q==="object"&&typeof q.toJSON==="function"&&!i&&(q=q.toJSON(j));typeof o==="function"&&(q=o.call(a,j,q));switch(typeof q){case "string":return e(q);case "number":return isFinite(q)?String(q):"null";case "boolean":case "null":return String(q);
case "object":if(!q)return"null";c+=g;h=[];if(Object.prototype.toString.apply(q)==="[object Array]"){d=q.length;for(b=0;b<d;b+=1)h[b]=l(b,q)||"null";m=h.length===0?"[]":c?"[\n"+c+h.join(",\n"+c)+"\n"+f+"]":"["+h.join(",")+"]";c=f;return m}if(o&&typeof o==="object"){d=o.length;for(b=0;b<d;b+=1)n=o[b],typeof n==="string"&&(m=l(n,q))&&h.push(e(n)+(c?": ":":")+m)}else for(n in q)Object.hasOwnProperty.call(q,n)&&(m=l(n,q))&&h.push(e(n)+(c?": ":":")+m);m=h.length===0?"{}":c?"{\n"+c+h.join(",\n"+c)+"\n"+
f+"}":"{"+h.join(",")+"}";c=f;return m}}var d={},i=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,g,k={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;d.stringify=function(j,b,a){var n;g=c="";if(typeof a==="number")for(n=0;n<a;n+=1)g+=" ";else typeof a==="string"&&(g=a);if((o=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return l("",{"":j})};d.parse=function(a,n){function c(a,
b){var j,g,d=a[b];if(d&&typeof d==="object")for(j in d)Object.hasOwnProperty.call(d,j)&&(g=c(d,j),g!==void 0?d[j]=g:delete d[j]);return n.call(a,b,d)}var g,a=String(a);b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+a+")"),
typeof n==="function"?c({"":g},""):g;throw new SyntaxError("JSON.parse");};var p={a:[1,2,3]},h,n;if(Object.toJSON&&Object.toJSON(p).replace(/\s/g,"")==='{"a":[1,2,3]}')h=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(p='{"a":[1,2,3]}'.evalJSON(),p.a&&p.a.length===3&&p.a[2]===3&&(n=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),i=!(a&&a.length===3&&a[2]===3))})();if(i||!h||!n)return{stringify:d.stringify,parse:d.parse};return{stringify:h,
parse:n}});
DISQUS.define(function(){function f(b){for(a=1;b=e.shift();)b()}var e=[],l,d=document,i=d.documentElement,b=i.doScroll,a=/^loade|c/.test(d.readyState),c;d.addEventListener&&d.addEventListener("DOMContentLoaded",l=function(){d.removeEventListener("DOMContentLoaded",l,!1);f()},!1);b&&d.attachEvent("onreadystatechange",l=function(){/^c/.test(d.readyState)&&(d.detachEvent("onreadystatechange",l),f())});c=b?function(b){self!=top?a?b():e.push(b):function(){try{i.doScroll("left")}catch(a){return setTimeout(function(){c(b)},50)}b()}()}:
function(b){a?b():e.push(b)};return{domready:c}});
DISQUS.define("Events",function(){var f=/\s+/,e={on:function(e,d,i){var b,a;if(!d)return this;e=e.split(f);for(b=this._callbacks||(this._callbacks={});a=e.shift();)a=b[a]||(b[a]=[]),a.push(d),a.push(i);return this},off:function(e,d,i){var b,a,c;if(!(a=this._callbacks))return this;if(!e&&!d&&!i)return delete this._callbacks,this;for(e=e?e.split(f):_.keys(a);b=e.shift();)if(!(c=a[b])||!d&&!i)delete a[b];else for(b=c.length-2;b>=0;b-=2)d&&c[b]!==d||i&&c[b+1]!==i||c.splice(b,2);return this},trigger:function(e){var d,
i,b,a,c,g,k;if(!(i=this._callbacks))return this;k=[];e=e.split(f);a=1;for(c=arguments.length;a<c;a++)k[a-1]=arguments[a];for(;d=e.shift();){if(g=i.all)g=g.slice();if(b=i[d])b=b.slice();if(b){a=0;for(c=b.length;a<c;a+=2)b[a].apply(b[a+1]||this,k)}if(g){d=[d].concat(k);a=0;for(c=g.length;a<c;a+=2)g[a].apply(g[a+1]||this,d)}}return this}};e.bind=e.on;e.unbind=e.off;return e});
DISQUS.define(function(f,e){function l(){throw Error(Array.prototype.join.call(arguments," "));}function d(a,b,c){if(a.addEventListener)a.addEventListener(b,c,!1);else if(a.attachEvent)a.attachEvent("on"+b,c);else throw Error("No event support.");}var i=f.document,b=DISQUS.use("JSON");if(!(DISQUS!==e&&DISQUS.version&&DISQUS.version()=="__version__")){var a={},c=0;d(f,"message",function(n){var j,c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)&&n.origin==a[c].origin){j=!0;break}if(j)switch(j=
b.parse(n.data),(c=a[j.sender])||l("Message from our server but with invalid sender UID:",j.sender),j.scope){case "host":c.trigger(j.name,j.data);break;case "global":DISQUS.trigger(j.name,j.data);break;default:l("Message",j.scope,"not supported. Sender:",n.origin)}},!1);d(f,"hashchange",function(){DISQUS.trigger("window.hashchange",{hash:f.location.hash})},!1);d(f,"resize",function(){DISQUS.trigger("window.resize")},!1);var g=function(){DISQUS.trigger("window.scroll")};(function(a,b,c,g){var e=(new Date).getTime();
d(a,b,function(){var a=(new Date).getTime();a-e>=g&&(e=a,c())})})(f,"scroll",g,250);(function(a,b,c,e){var g;d(a,b,function(a){g&&clearTimeout(g);g=setTimeout(function(){c(a)},e)})})(f,"scroll",g,300);i.getElementsByTagName("html");d(f,"click",function(){DISQUS.trigger("window.click")});g=function(){this.uid=c++};DISQUS.extend(g.prototype,DISQUS.Events);var k=function(a){a=a||{};this.isReady=!1;this.uid=a.uid||c++;this.elem=null;this.styles={}};k.prototype.load=function(){var a=this.elem=i.createElement("iframe");
a.setAttribute("id","dsq"+this.uid);a.setAttribute("data-disqus-uid",this.uid);a.setAttribute("allowTransparency","true");a.setAttribute("frameBorder","0");for(var b in this.styles)this.styles.hasOwnProperty(b)&&(a.style[b]=this.styles[b])};var o=function(b){var c=this;k.call(c,b);c.listeners={};c.origin=b.origin;c.target=b.target;c.container=b.container;c.styles={width:"100%",border:"none",overflow:"hidden",display:"none"};a[c.uid]=c;c.on("ready",function(){c.isReady=!0})};o.prototype.load=function(a){k.prototype.load.call(this);
var b=this.elem;b.setAttribute("width","100%");b.setAttribute("src",this.target+"#"+this.uid);d(b,"load",function(){b.style.display="";a&&a()});(i.getElementById(this.container)||i.body).appendChild(b);this.elem=b};o.prototype.sendMessage=function(a,c){var d=function(a,b,c){return function(){c.elem.contentWindow.postMessage(a,b)}}(b.stringify({scope:"client",data:{eventName:a,data:c}}),this.origin,this);if(this.isReady)d();else this.on("ready",d)};o.prototype.getPosition=function(){for(var a=this.elem,
b=0,c=0;a;)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return{top:c,left:b}};o.prototype.inViewport=function(a){var a=a||this.getPosition(),a=a.top,b=a+this.elem.offsetHeight,c=f.pageYOffset;return!(a>c+f.innerHeight||b<c)};o.prototype.destroy=function(){this.off();this.elem&&this.elem.parentNode.removeChild(this.elem)};DISQUS.extend(o.prototype,DISQUS.Events);var p=function(a){k.call(this,a);this.contents=a.contents;this.container=a.container;this.styles={width:"100%",border:"none",overflow:"hidden"};
a.styles=a.styles||{};for(var b in a.styles)a.styles.hasOwnProperty(b)&&(this.styles[b]=a.styles[b])};p.prototype.load=function(){k.prototype.load.call(this);var a=this.elem;a.setAttribute("scrolling","no");(i.getElementById(this.container)||i.body).appendChild(a);this.element=a;this.window=a.contentWindow;try{this.window.document.open()}catch(b){a.src="javascript:var d=document.open();d.domain='"+i.domain+"';void(0);"}this.document=this.window.document;this.document.write(this.contents);this.document.close();
if(a=this.document.body)this.element.style.height=a.offsetHeight+"px"};p.prototype.exec=function(a){a.call(this,this.window,this.document)};p.prototype.hide=function(){var a=this.element.style.display;if(a!=="none")this._display=a;this.element.style.display="none"};p.prototype.show=function(){this.element.style.display=this._display||"block"};p.prototype.click=function(a){d(this.document.body,"click",function(b){a(b)})};var h=DISQUS.extend({},DISQUS.Events);return{IFRAME:"__widget_iframe__",log:function(a){var b=
i.getElementById("messages");if(b){var c=i.createElement("p");c.innerHTML=a;b.appendChild(c)}},version:function(){return"__version__"},on:h.on,off:h.off,trigger:h.trigger,Channel:o,Sandbox:p,App:g}}});
DISQUS.define(function(){function f(e){DISQUS.App.call(this);this.switches={};this.frame=new DISQUS.Channel({target:"http://mediacdn.disqus.com/1342822987/build/next-switches/client.html",container:e.container,origin:"http://mediacdn.disqus.com"});var f=this;this.frame.load(function(){f.frame.elem.style.display="none"})}f.prototype=DISQUS.extend({fetch:function(e){var f=this,e=e||{},d=e.success;delete e.success;this.frame.on("switches.received",function(e){f.switches=e;DISQUS.trigger("switches.changed",
e);d&&d(e)});this.frame.sendMessage("fetch",e)},enabled:function(e){return this.switches[e]?this.switches[e]:!1}},DISQUS.App.prototype);return{Switches:function(e){return new f(e)}}});
DISQUS.define(function(f,e){function l(a,b,d,e,f,h){return'<img width="'+a+'" height="'+b+'" alt="'+e+'" src="data:image/'+d+";base64,"+f+'"'+(h?'style="'+h+'"':"")+"/>"}var d=f.document,i=["iVBORw0KGgoAAAANSUhEUgAAAEcAAAARCAYAAAH4YIFjAAAAGXRFWHRTb2Z0d2FyZQBB","ZG9iZSBJbWFnZVJlYWR5ccllPAAABwdJREFUeNpi/P//PwMhwAIiGBkZGeK6V8JVh9rq","dfrc0ixnEDb+wPD2rAAjMSYBBBBRisDWwKxCthIE/q8Q+A8yhCiTAAIIrCi+ZxVMZSAQ","r19UGs4IMxWd/X8Rw3/GOKDhW43fgzwF1hX7n5EJ2dSp2QFNUKcZwJ31/78CkvPBGkGG","MXidSUTWCxBAxAUAEQAcJzCvIXsDBPwsNBU2nbj+AMpdsFA8PAHsLZj3QC5D9hrIAEtN",
"+RMwAzRkxcB0iK3eQ6iQIRAnoMTE//8CyHwmWHQdv/7QAiZ44/ErMP383acsqNB5iMnP","lsFdsUZ6IU3CCCCA4AYBw8kBJgj06gGkmHJAFgPyQV4ExeQEoNgHJHUBQMoAWRzoerBe","YHgeQOJ/APIvQPkNUP4EuIdADBAGBRMQOABxQcakdSipHZldNGvL2zWHL8kD1d0HieVN","33QYqnc/EAfULNwJVw8KTniQwvjAdPz/SEwKmL1KfC5QjwEQr4e5AyVdA3P4ASCe8O3n","b1whmtib6r3IXlfpATBEFbpWH9ygJSdmBtXrOHPbyZWPXn1AqOZRwDSBS+YHo82SOQwi","ZnYMoS+EGC42nGdYzBiAnKpgGAbeA3ECkjwYQNnzH758///6o5cgofVIagy+/vgFF//y","/ecHJLn1/18AA+/teZBcPZL4eSTxBJg7AAKIaomRmpkeV2IG5UcDpMSsAM2zF4BiG9DU","FaCLQxPwBWCC/QBkg/QqoCVuEN4ASuDIaWc/DIMSItBxH0GCrkaqCVBxWO4BJWBQcK/P",
"mrL+I1S8H0i9h4mjFfX7GTRyIdEuHzIfZtb/Zdw3oGyQnvP/d9pNgRc+MLCwJMxxWk7A","I6Ar+YCWVSLLyYkJzIYlZqC6RGBhbg/lFwDlQHoDgfgALLfhjY8/X9XhpWPs/wWM7ody","MBwDylU8nOzyILYIH3cZslxBgM0cKHM+MOTAGCZnri7XCdS7ASgGLsc/fPlug9cxlrO/","wUvYxYwJwCgLwHAMcrVlqCJ9BVlchJ+7EhRyQPwAyGaAFnhgsOPMzUhQroLVAU76yp/g","Gp/vtQbTr45pwMWOp1oDQ6QQiGEi6+EJGLmah0YJQ6CVtu3ivecKYHIpE9b8BPqcDSna","wHSSu8m3eTvPyAHlzsPkDl25/wXMYAOq+XgtBFwIfn/GwCAOSq8HYCGCsNh8+hvksgYZ","IJchDkjljAKoHAKVJ6ByBbnmA5XESOL1oFIZSc9/cJkC1IukPuH/z/cw8fswdwyqcgYg","wAaVYwYbQEnDSI1LbGABEDcCC1lYS4yhfO42n+fvPm9GKsAZkfJDA7RcwwYmQM1CbpUU",
"ADU3AB3AjxJ7wFwAFGsAqp2A0mBDahww8Gv4Mvrf2AKXWyMzgeHbk3wwh5X/DGPkR1Oo","HlCmn49cGCABkL8SgZn8ANbAQQaV4ZBK6yGwgbDr3G2GNx+/gkqShMTe1V///vsnA/KY","joKECjBwMPQCW0EngOrNQWxbHQWGFA8zBlAj5eztpwwbjl9lyPG1DFOUEAIFDqxJB6ks","oC1ZN2NVsDm7zt4GNUhBgdUPrXwckWtQOJB0VQE2XRF8UQt9hodrIGw+FaDcWVjAwAsh","hsD7kAbPO2Dr78ZEBoZfHxQYHNYbwEogvIGjKSfOiNysBpaEL/acv8MODBhuUX7u00Bh","VVx6DZWlxHcDAxQEDl95AMZQAGqHLlSSFIanAnZWll0/f/8Bs2OcDB+5GavJVyGZtevs","rYdL9p2XQ6rZGcnKI54nZRj2uoMCAVr4K8JkQAKgJsdEYN12AbmYYSGqYGJk/NC8bO91","WHKUFRXgwace6ElDIF4PjHWHc3eeMZy98xSU8mB1mwE0FSQCU8ECZiZGVpi+yw9eLIfV",
"lUyMjIf+/f/Pu/bIlTtIdSX5hauo+RagxxMZfr2fwHB3IT/Dy4MMDI/BzTABaP2aAGzm","gPpN4gQDB1pmgIA+EAfcfvoGXl/mB1hXFuBxCLDs6oc26kBJZiIoxShLCqs9e/tp+vdf","v8ENB08Tdf9FwHKsMtxxTfvK/SGgbHfx3vNyoL2g7DjR30r74vqjV2yA6lXgbnI2WtoH","4yhEfGF4sAISSTcm9wOzDcidoE6lPTBLwRuyDMoJ5+DZagnLJIb/f3mh5edGcKoRs+5n","eHUUUgZxiIrhrK2wFchc7KwMmsByANjiAZUfoGzhCEpJIDlQowOYffqRC2RQS+f1x68H","Nx6/ygcqY9A7RMZAc5LcTS/zcLLZwcwB1evAzs/8pfsvwDu9yOplgRECzF4M8a7Gryw0","5NRB+sDtiC/3HjKcKeaDpgAEADVmNIDlsX4DqFPmCOvvMNxdkAAuX95dQFUPKnv06kEB","mQgNOLpV5QbQpAsrcz4QUC+AVJsgqxcgoNcBqQy5QIIdONUDALcn6c0dtMJ9AAAAAElF",
"TkSuQmCC"],b=["R0lGODlhEAALAPQAAP///z2LqeLt8dvp7u7090GNqz2LqV+fuJ/F1IW2ycrf51aatHWs","waXJ14i4ys3h6FmctUCMqniuw+vz9eHs8fb5+meku+Tu8vT4+cfd5bbT3tbm7PH2+AAA","AAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQu","aW5mbwAh+QQJCwAAACwAAAAAEAALAAAFLSAgjmRpnqSgCuLKAq5AEIM4zDVw03ve27if","DgfkEYe04kDIDC5zrtYKRa2WQgAh+QQJCwAAACwAAAAAEAALAAAFJGBhGAVgnqhpHIeR","vsDawqns0qeN5+y967tYLyicBYE7EYkYAgAh+QQJCwAAACwAAAAAEAALAAAFNiAgjoth","LOOIJAkiGgxjpGKiKMkbz7SN6zIawJcDwIK9W/HISxGBzdHTuBNOmcJVCyoUlk7CEAAh",
"+QQJCwAAACwAAAAAEAALAAAFNSAgjqQIRRFUAo3jNGIkSdHqPI8Tz3V55zuaDacDyIQ+","YrBH+hWPzJFzOQQaeavWi7oqnVIhACH5BAkLAAAALAAAAAAQAAsAAAUyICCOZGme1rJY","5kRRk7hI0mJSVUXJtF3iOl7tltsBZsNfUegjAY3I5sgFY55KqdX1GgIAIfkECQsAAAAs","AAAAABAACwAABTcgII5kaZ4kcV2EqLJipmnZhWGXaOOitm2aXQ4g7P2Ct2ER4AMul00k","j5g0Al8tADY2y6C+4FIIACH5BAkLAAAALAAAAAAQAAsAAAUvICCOZGme5ERRk6iy7qpy","HCVStA3gNa/7txxwlwv2isSacYUc+l4tADQGQ1mvpBAAIfkECQsAAAAsAAAAABAACwAA","BS8gII5kaZ7kRFGTqLLuqnIcJVK0DeA1r/u3HHCXC/aKxJpxhRz6Xi0ANAZDWa+kEAA7","AAAAAAAAAAAA"],
a=function(a){DISQUS.App.call(this);this.settings=a;this.indicators={north:null,south:null};this._boundGlobalEvents=[];this.frame=null};a.prototype.init=function(){function a(b,c){g._boundGlobalEvents.push(b);DISQUS.on(b,c,g)}var g=this,k=g.settings,o={f:k.forum,t_i:k.identifier,t_u:k.url||f.location.href,t_s:k.slug,t_t:k.title,s_o:k.sortOrder,c:k.useConman},p=DISQUS.isString(k.container)?d.getElementById(k.container):k.container,h=g.frame=new DISQUS.Channel({origin:"http://disqus.com",target:DISQUS.serialize("http://disqus.com/next/lounge/client.html",
o),container:k.container,uid:"embed-"+this.uid}),n=!1;if(f.postMessage){var j=d.createElement("div");j.innerHTML=l(71,17,"png","DISQUS",i.join(""))+l(16,11,"gif","...",b.join(""),"margin:0 0 3px 5px");p.appendChild(j)}o=function(){var a=h.getPosition(),b=f.pageYOffset,c=f.innerHeight,m=h.inViewport(a);m?(n=!0,h.sendMessage("window.scroll",{frameOffset:a,pageOffset:b,height:c}),h.sendMessage("window.inViewport")):n&&!m&&(n=!1,h.sendMessage("window.scrollOffViewport"))};h.on("ready",function(a){p.removeChild(j);
var b={themeUrl:k.themeUrl,permalink:k.permalink,anchorColor:k.anchorColor,referrer:f.location.href,colorScheme:k.colorScheme,serif:k.serif,remoteAuthS3:k.remoteAuthS3,apiKey:k.apiKey,sso:k.sso};if(f.navigator.userAgent.match(/(iPad|iPhone|iPod)/))b.width=h.elem.offsetWidth;h.inViewport()&&h.sendMessage("window.inViewport");g.clientData=a;h.sendMessage("init",b);g.trigger("loading.init")});h.on("resize",function(a){h.elem.style.height=a.height+"px"});h.on("reload",function(){f.location.reload()});
h.on("posts.paginate",function(){g.trigger("posts.paginate")});h.on("posts.create",function(a){g.trigger("posts.create",{id:a.id,text:a.raw_message})});h.on("scrollTo",function(a){var b=h.getPosition(),b=a.relative==="window"?a.top:b.top+a.top;(a.force||!(b>f.pageYOffset&&b<f.pageYOffset+f.innerHeight))&&f.scrollTo(0,b)});h.on("fakeScroll",o);h.on("realtime.init",function(a){for(var b=["north","south"],c,m,d=0;d<b.length;d++)m=b[d],c=new DISQUS.Sandbox({uid:"-indicator-"+m,container:g.settings.container,
contents:a[m].contents,styles:a[m].styles}),c.load(),c.hide(),function(a){c.click(function(){h.sendMessage("realtime.click",a)})}(m),g.indicators[m]=c});h.on("realtime.showNorth",function(a){var b=g.indicators.north;b.document.getElementById("message").innerHTML=a;b.show()});h.on("realtime.hideNorth",function(){g.indicators.north.hide()});h.on("realtime.showSouth",function(a){var b=g.indicators.south;b.document.getElementById("message").innerHTML=a;b.show()});h.on("realtime.hideSouth",function(){g.indicators.south.hide()});
h.on("mainViewRendered",function(){DISQUS.trigger("lounge:mainViewRendered");g.trigger("loading.done")});h.load(function(){f.postMessage===e&&(h.elem.setAttribute("height","500px"),h.elem.setAttribute("scrolling","yes"),h.elem.setAttribute("horizontalscrolling","no"),h.elem.setAttribute("verticalscrolling","yes"))});a("window.hashchange",function(a){h.sendMessage("window.hashchange",a.hash)});a("window.resize",function(){h.sendMessage("window.resize")});a("window.scroll",o);a("window.click",function(){h.sendMessage("window.click")});
a("switches.changed",function(a){h.sendMessage("switches.changed",a)});g.trigger("loading.start")};a.prototype.destroy=function(){this.off();DISQUS.off(this._boundGlobalEvents.join(" "),null,this);this._boundGlobalEvents=[];this.frame&&this.frame.destroy()};DISQUS.extend(a.prototype,DISQUS.App.prototype);return{Lounge:function(b){return new a(b)}}});
(function(f,e,l){function d(){function a(b){var b=b.getAttribute?b.getAttribute("src"):b.src,c=[/https?:\/\/(www\.)?disqus\.com\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.disqus\.com/i,/https?:\/\/(www\.)?dev\.disqus\.org\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.dev\.disqus\.org/i],d=c.length;if(!b||b.substring(b.length-8)!="embed.js")return null;for(var m=0;m<d;m++){var e=b.match(c[m]);if(e&&e.length&&e.length==3)return e[2]}return null}for(var b=e.getElementsByTagName("script"),
c=b.length-1;c>=0;c--){var d=a(b[c]);if(d!==null)return d}return null}function i(a,b,c){var d;if(a===e)return"";f.getComputedStyle?d=e.defaultView.getComputedStyle(a,null).getPropertyValue(b):a.currentStyle&&(d=a.currentStyle[b]?a.currentStyle[b]:a.currentStyle[c]);return d=="transparent"||d===""||d=="rgba(0, 0, 0, 0)"?i(a.parentNode,b,c):d||null}function b(b){b.match("^rgb")&&(b=a(b).substr(1));var c=parseInt(b.substr(0,2),16),d=parseInt(b.substr(2,2),16),b=parseInt(b.substr(4,2),16);return(c*299+
d*587+b*114)/1E3}function a(a){function b(a){a=Number(a).toString(16);return a.length==1?"0"+a:a}if(a.substr(0,1)==="#")return a;var c=/.*?rgb\((\d+),\s*(\d+),\s*(\d+)\)/.exec(a);if(!c||c.length!==4)return"";var a=b(c[1]),d=b(c[2]),c=b(c[3]);return"#"+a+d+c}function c(a,b,c){DISQUS.isString(a)&&(a=e.createElement(a));var d=null;a.style.visibility="hidden";h.appendChild(a);d=i(a,b,c);h.removeChild(a);return d}function g(){var a=e.createElement("a");a.href=+new Date;return c(a,"color")}function k(){for(var a=
e.getElementsByTagName("h1"),b=e.title,c=b.length,d=b,g=0.6,f=0;f<a.length;f++)(function(a){var a=a.textContent||a.innerText,e;if(!(a===null||a===l)){e=0;for(var f=Array(b.length),h=0;h<=b.length;h++){f[h]=Array(a.length);for(var m=0;m<=a.length;m++)f[h][m]=0}for(h=0;h<b.length;h++)for(m=0;m<a.length;m++)b[h]==a[m]&&(f[h+1][m+1]=f[h][m]+1,f[h+1][m+1]>e&&(e=f[h+1][m+1]));e/=c;e>g&&(g=e,d=a)}})(a[f]);return d}function o(){var a=j.page,a={container:p,forum:s,anchorColor:g(),colorScheme:128<b(c("span",
"color"))?"dark":"light",sortOrder:"popular",permalink:n,serif:{courier:1,times:1,georgia:1,palatino:1}.hasOwnProperty(c("span","font-family","fontFamily").toLowerCase()),url:a.url||f.location.href.replace(/#.*$/,""),title:a.title||k(),slug:a.slug,category:a.category_id,identifier:a.identifier,apiKey:a.api_key,remoteAuthS3:a.remote_auth_s3,sso:j.sso,themeUrl:f.disqus_theme_root_url,useConman:f.disqus_demo};r=DISQUS.Lounge(a);var d={onReady:"loading.done",onNewComment:"posts.create",onPaginate:"posts.paginate"};
DISQUS.each(j.callbacks,function(a,b){d[b]&&DISQUS.each(a,function(a){r.on(d[b],a)})});r.init()}var p=f.disqus_container_id||"disqus_thread",h=e.getElementById(p),n=function(){var a=f.location.hash;return(a=a&&a.match(/comment\-([0-9]+)/))&&a[1]}(),j={page:{url:l,title:l,slug:l,category_id:l,identifier:l,api_key:l,remote_auth_s3:l,author_s3:l,developer:l},sso:{},callbacks:{preData:[],preInit:[],onInit:[],afterRender:[],onReady:[],onNewComment:[],preReset:[],onPaginate:[]}};DISQUS.each(["developer",
"shortname","identifier","url","title","category_id","slug"],function(a){var b=f["disqus_"+a];typeof b!=="undefined"&&(j.page[a]=b)});var s=f.disqus_shortname||d(),s=s.toLowerCase();if(typeof f.disqus_config==="function")try{f.disqus_config.call(j)}catch(t){}var r;e.getElementById(p).innerHTML="";o();if(f.postMessage)DISQUS.Switches({container:p}).fetch({data:{forum:s}}),DISQUS.domready(function(){if(e.getElementsByClassName){var a=e.getElementsByClassName("dsq-brlink");a&&a.length&&a[0].parentNode.removeChild(a[0])}}),
DISQUS.request={get:function(a,b,c){DISQUS.require(a,b,c)}},DISQUS.reset=function(a){a=a||{};if(typeof a.config==="function")try{a.config.call(j)}catch(b){}r&&(r.destroy(),r=null);a.reload&&o()}})(this,this.document);